# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Help | Cloud 66
email: support@cloud66.com
permalink: /:categories/:title.html

collections:
  rails:
    output: true
    permalink: /:collection/:categories/:name
    icon: foundicon-idea
  node:
    output: true
    permalink: /:collection/:categories/:name
    icon: foundicon-idea

# Build settings
markdown: kramdown

sass:
    style:  compressed  # nested|expanded|compact|compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
